### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by fgent** [OCSInventory-NG/Packager-for-Windows#1]
ListBox and instOCS are fine but I get an error when compiling OcsPackager.nsi

!include: could not find: "TextReplace.nsh"
Error in script "...OcsPackager.nsi" on line 16 -- aborting creation process

When commenting this line, I get many further errors, even worse.
Any idea ?

**Comment by fbomj** [comment]
Hi,

You have to install TextReplace.nsh plugin for NSI. http://nsis.sourceforge.net/TextReplace_plugin

Regards

Frank

**Comment by fgentner** [comment]
Thanks Frank,
Now after plugin install, I get a new similar message :
Plugin not found, cannot call textreplace::_ReplaceInFile
Error in macro textreplace::ReplaceInFile on macroline 1
Error in script "...OcsPackager.nsi" on line 256 -- aborting creation process

**Comment by tkroals** [comment]
Hi fgent,

check where is your plugin directory after running OcsPackager.nsi (5th line),  put there TextReplace.dll and run it again.

It should look like this:

MakeNSIS v3.01 - Copyright 1999-2016 Contributors
See the file COPYING for license details.
Credits can be found in the Users Manual.

Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
**Processing default plugins: "C:\Program Files (x86)\NSIS\Plugins\x86-ansi\*.dll"**
