### ISSUE TITLE
Provide uninstall Agent then plugins install last setup Agent

### ISSUE THREAD

**Issue by keyoneplus** [OCSInventory-NG/Packager-for-Windows#2]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Window 10

### OCS Inventory informations
Windows agent version :  2.3.0.0

### Problem's description
*Describe your problem here*

Doing upgrade from 2.1.1.1 to 2.3.0.0 (WINDOWS agent) in silent mode, via remote.  Do not provide uninstallation.

Is better to provide clear up old files from 2.1.1.1 agent when doing an upgrade to 2.3.0.0.  There an /upgrade option but only valid for 1.x Agent which is long time ago. Hope there an /upgrade=previous_agent_folder_path ( to run uninst.exe) this will provide a clean uninstallation then transfer plugins files and last the new agent setup process (NSIS_agent_setup) .  So unnecessary old files  is clear (fig2)

 Fig 1
![image](https://user-images.githubusercontent.com/5064672/31429929-f3281afe-aea1-11e7-8904-61bbda8076d3.png)
Fig 2
![image](https://user-images.githubusercontent.com/5064672/31429949-0298ded8-aea2-11e7-811a-43b56aaf897a.png)

Thanks.

**Comment by gillesdubois** [comment]
Hi,

Your problem can come from 2 things : 
- Your packager (ocspackage.exe) is not launched as administrator so he can stop services and remove used files
- You didn't set the /UPGRADE option

The /UPGRADE is not for agent coming from 1.X only.
It's used for every agent update and make the installer check for process and kill them.

Regards,
Gilles Dubois.

**Comment by keyoneplus** [comment]
1)  Ocspackage.exe is launch with Administrator privileges
![image](https://user-images.githubusercontent.com/5064672/31474716-0f8b01ba-af2f-11e7-99ba-4493fb9f737b.png)

2) The Command line is: "C:\Users\keyone\AppData\Local\Temp\nsfF9C6.tmp\OcsSetup.exe"  /server=http://myocs/ocsinventory /no_systray /ssl=1 /now /s /upgrade.
where ocspackage.exe will trigger Setup.exe , it did kill the processes OcsSystray.exe, OcsService.exe  and so on. However it did not delete unnecessary lib files.  It simple just copying over(3).
![image](https://user-images.githubusercontent.com/5064672/31474792-9b837030-af2f-11e7-8cd4-89614977d18d.png)

The setup.exe did not handle delete of unwanted lib files. 
Suggest that the ocspackage.exe can run uninstall process before the transfer of plugin and setup begin.  In this sequence the plugins file will be clear.

**Comment by keyoneplus** [comment]
Other issue : is the killing process base on one off or  time out
1) cmdline without /UPGRADE , it will still try to stop service (2) , then time out, proceed to kill process with timeout (3)  show no error. then proceed to copy new file.  And the OcsService.exe have error during copying, this because i use another process  to open it to simulate the error.  
with /UPGRADE  it will provide "
Writing setup result <SUCCESS> for Package ID <> to file <C:\ProgramData\OCS Inventory NG\Agent\Download\OCSNG-Windows-Agent-Setup_done>" 

![image](https://user-images.githubusercontent.com/5064672/31476489-2f77b9f0-af39-11e7-8587-c48addf9f173.png)

**Comment by kiquenet** [comment]
how install OCS Inventory in Windows ? step by step ?
