### ISSUE TITLE
Newbie with OCS Inventory

### ISSUE THREAD

**Issue by kiquenet** [OCSInventory-NG/Packager-for-Windows#3]
How-to use OCS Inventory in Windows?

error 404
http://ask.ocsinventory-ng.org/
http://wiki.ocsinventory-ng.org/index.php/Main_Page

No info :'(

any step-by-step guide, or Getting Started – Quick Start that can be completed in 15-20 minutes?

I get you a good step-by-step guide sample like https://berniecook.wordpress.com/2013/01/13/getting-started-with-git-and-visual-studio-step-by-step-guide/ 4

… I wanted to quickly cover off several assumptions before we get started: install (requisites, tools required), configure, an running quickly. Target will be an “go and ready” sample. Maybe better an real application sample

Mindly notes:

Any good getting started with ElasticSearch? step by step in 10 minutes?

IMHO, better samples for minimize learning curve are real applications with full source code and good patterns and practices

Full source code sample REAL application? not Demo, only real applications?
Like for small to medium applications development, but open source, if you can sharing or maybe another real project or production-ready application using.

main influences, are full of innovative ideas that can free our minds to explore new techniques, patterns and paradigms.

You want to use technologies that allow for rapid development, constant iteration, maximal efficiency, speed, robustness and more. You want to be lean and you want to be agile. You want to use technologies that will help you succeed in the short and long term. And those technologies are not always easy to pick out.

Thanks a lot for your big efforts.

**Comment by gillesdubois** [comment]
Hi,

OCS Inventory's Wiki is now better and clearer.
I think most of the Wiki content can now anwser most of your problems.

Regards,
Gilles Dubois.
