### ISSUE TITLE
Package with upgrade function

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/Packager-for-Windows#4]
How to create a package with upgrade function (like a /DEPLOY key for ocslogon.exe)?
I need install the agent only in next cases:
- there're not an agent on a PC;
- current version of the agent on a PC is less than in the package.

But I get the installation of the agent in all cases, even if current version of the agent on a PC is equal the package version.

There's a problem if the package starts with Active Directory GPO.

**Comment by gillesdubois** [comment]
Hi,

Please re-open an issue if you need more assistance. This issue is rather old and not reveleant with the current tools available with OCS.

Regards,
Gilles Dubois.
