### ISSUE TITLE
Packager 2.3 create package with default options

### ISSUE THREAD

**Issue by antoniotvr** [OCSInventory-NG/Packager-for-Windows#5]
Hi.

I have created a package for Windows with OCSNG-Windows-Agent-2.4.0.0 and OCSNG-Windows-Packager-2.3.

I have launched packger, setup variuos option and then create the package.

But when I install the package on my PC the installed packages has default options (I have looked in AppData and ocsinventory.ini does not contain the custom voices that I have inseted during installation).

Can you help me?

Thank you

**Comment by gillesdubois** [comment]
Hi,

The newest versions of the packager doesn't encounter this problem.
Thus i'm closing this issue.

Gilles.
